// Alimentation Première — Catalogue complet (259 produits)
export const CATEGORIES = ['Boeuf','Poulet','Porc','Poisson','Veau et Agneau','Gibier','Plats','Desserts'];

export const PRODUCTS = [
  {code:'821397',category:'Boeuf',name:'Bœuf haché 92%, Sans Abats',format:'10 x 454g',origin:'Produit Canadien',price:102.0},
  {code:'821343',category:'Boeuf',name:'Cubes de bœuf à mijoter',format:'8 x 454g',origin:'Produit d\'Alberta',price:104.0},
  {code:'811222',category:'Boeuf',name:'Rôti de haut de ronde (rosbif)',format:'3 x 1kg',origin:'Produit d\'Alberta',price:114.0},
  {code:'821425',category:'Boeuf',name:'Rôti de palette désossé',format:'3 x 1kg',origin:'Produit d\'Alberta',price:94.0},
  {code:'811625',category:'Boeuf',name:'Biftek minute de ronde AA',format:'24 x 110g',origin:'Produit d\'Alberta',price:139.0},
  {code:'821527',category:'Boeuf',name:'Haut de surlonge 6oz (Baseball)',format:'12 x 170g',origin:'Canadian premium beef',price:154.0},
  {code:'821528',category:'Boeuf',name:'Haut de surlonge 8oz (Baseball)',format:'12 x 220g',origin:'Canadian premium beef',price:174.0},
  {code:'811430',category:'Boeuf',name:'Bifteck Chateaubriand',format:'8 x 280g',origin:'Spring Creek',price:199.0},
  {code:'666023',category:'Boeuf',name:'Steak mariné au poivre',format:'18 x 180g',origin:'Produit du québec',price:139.0},
  {code:'666024',category:'Boeuf',name:'Trio de steak mariné ( au poivres, vin rouge, épices steak house)',format:'18 x 180g',origin:'Produit du québec',price:139.0},
  {code:'121131',category:'Boeuf',name:'Tournedos de bœuf au bacon',format:'15 x 150g',origin:'Spring Creek',price:144.0},
  {code:'121151',category:'Boeuf',name:'Tournedos de bœuf aux trois poivres',format:'15 x 150g',origin:'Spring Creek',price:144.0},
  {code:'821804',category:'Boeuf',name:'Pavé de bœuf mijoté dans une sauce à la bière',format:'2 kg',origin:'Véritable',price:104.0},
  {code:'811164',category:'Boeuf',name:'Steak Cowboy généreux pour amateurs de viande',format:'2.5 kg',origin:'Produits Alimentaires LM',price:134.0},
  {code:'821368',category:'Boeuf',name:'Rosette de bœuf farcie au fromage et poivrons',format:'2 kg',origin:'Alberta beef',price:104.0},
  {code:'150322',category:'Boeuf',name:'Smoked meat sans gluten',format:'6 x 454g',origin:'Délecta',price:154.0},
  {code:'811116',category:'Boeuf',name:'Lanières de bœuf braisées, mijoté dans une sauce bordelaise',format:'6 x 400g',origin:'Produits Alimentaires LM',price:129.0},
  {code:'821803',category:'Boeuf',name:'Joues de bœuf',format:'3 x 2un',origin:'Véritable',price:124.0},
  {code:'811117',category:'Boeuf',name:'Brochettes de filet mignon et bacon',format:'6 x (2 x 200g)',origin:'Produits Alimentaires LM',price:184.0},
  {code:'141197',category:'Boeuf',name:'Burger premium Northern Gold',format:'24 x 150g',origin:'Canadian premium beef',price:124.0},
  {code:'821529',category:'Boeuf',name:'Onglet AAA+, pièce tendre au goût intense',format:'12 x 170g',origin:'Canadian premium beef',price:144.0},
  {code:'821424',category:'Boeuf',name:'Macreuse AAA+, incontournable pour le souper',format:'12 x 190g',origin:'Canadian premium beef',price:169.0},
  {code:'821416',category:'Boeuf',name:'Bavette AAA+, parfaite pour le BBQ',format:'12 x 225g',origin:'Canadian premium beef',price:234.0},
  {code:'821420',category:'Boeuf',name:'Faux filet Northern Gold tendre et juteux',format:'10 x 280g',origin:'Canadian premium beef',price:329.0},
  {code:'821417',category:'Boeuf',name:'Contre-filet AAA+ au persillage généreux',format:'12 x 280g',origin:'Canadian premium beef',price:344.0},
  {code:'821423',category:'Boeuf',name:'Filet mignon Northern Gold, la coupe la plus tendre',format:'10 x 224g',origin:'Canadian premium beef',price:379.0},
  {code:'821429',category:'Boeuf',name:'Bifteck de côte 1" épais, idéal pour grillades',format:'6 x 450g    (2,7 kg)',origin:'Canadian premium beef',price:204.0},
  {code:'821419',category:'Boeuf',name:'Bifteck de côte 1"1/2extra épais pour amateurs sérieux',format:'4 x 675gr  (2.7 kg)',origin:'Canadian premium beef',price:204.0},
  {code:'821436',category:'Boeuf',name:'Biftek T-Bone (Aloyau) AAA généreux et savoureux',format:'4 x 750g       (3 kg)',origin:'Canadian premium beef',price:204.0},
  {code:'821426',category:'Boeuf',name:'Tomahawk AAA spectaculaire et marbré',format:'2 x +/-1,5 kg',origin:'Canadian premium beef',price:194.0},
  {code:'AP1698',category:'Boeuf',name:'Boite découverte Wagyu pour fins gourmets',format:'8 produits',origin:'Cuisine du marché',price:194.0},
  {code:'666015',category:'Boeuf',name:'Bœuf haché de wagyu',format:'6 x 454gr',origin:'Wagyu Québec',price:134.0},
  {code:'666007',category:'Boeuf',name:'Fondue chinoise de wagyu',format:'6 x 200gr',origin:'Wagyu Québec',price:159.0},
  {code:'666012',category:'Boeuf',name:'Sauce à spaghetti de wagyu',format:'4 x 750gr',origin:'Wagyu Québec',price:114.0},
  {code:'821552',category:'Boeuf',name:'Haut de surlonge Wagyu “baseball”, tendre et pleine de goût',format:'10 x 200g',origin:'Sir Harry',price:234.0},
  {code:'821536',category:'Boeuf',name:'Bavette Wagyu extrêmement fondante',format:'10 x 170g',origin:'Sir Harry',price:314.0},
  {code:'821533',category:'Boeuf',name:'Contre-filet Wagyu grade 8-9 au persilllage luxueux',format:'8 x 280g',origin:'Sir Harry',price:604.0},
  {code:'821535',category:'Boeuf',name:'Filet mignon Wagyu grade 9-8, super délicat',format:'10 x 170g',origin:'Sir Harry',price:604.0},
  {code:'821553',category:'Boeuf',name:'Faux filet Wagyu grade 8-9 aux saveurs riches et raffinées',format:'10 x 300g',origin:'Sir Harry',price:554.0},
  {code:'301142',category:'Poulet',name:'Poitrine de poulet désossée format familial',format:'+/-2,7kg',origin:'Produit du Québec',price:82.0},
  {code:'920852',category:'Poulet',name:'Poulet entier fermier tendre et juteux',format:'+/-2kg',origin:'Produit du Québec',price:21.99},
  {code:'821411',category:'Poulet',name:'Cuisse de poulet généreuse et savoureuse',format:'+/- 6 x 600gr',origin:'Produit du Québec',price:64.0},
  {code:'2433',category:'Poulet',name:'Pilon de poulet',format:'+/-6 x 900g',origin:'Produit du Québec',price:74.0},
  {code:'821341',category:'Poulet',name:'Ailes de poulet nature complète pleine de saveur',format:'+/-6 x 750g',origin:'Produit du Québec',price:74.0},
  {code:'811339',category:'Poulet',name:'Haut de cuisse désossé extra tendre',format:'+/-6 x 600g',origin:'Produit du Québec',price:114.0},
  {code:'821333',category:'Poulet',name:'Escalope de poulet fine et fondante',format:'20 x 120g',origin:'Le poulet du Québec',price:114.0},
  {code:'821465',category:'Poulet',name:'Poulet haché maigre et polyvalent',format:'6 x 450g',origin:'Ferme des voltigeurs',price:74.0},
  {code:'811346',category:'Poulet',name:'Poitrine de poulet au miel et ail savoureusement marinée',format:'12 x 170g',origin:'Le poulet du Québec',price:114.0},
  {code:'811347',category:'Poulet',name:'Poitrine de poulet sauce BBQ fumée',format:'12 x 170g',origin:'Le poulet du Québec',price:114.0},
  {code:'821370',category:'Poulet',name:'Poitrine de poulet farcie brocoli et fromage fondant',format:'10 x 270g',origin:'Le poulet du Québec',price:144.0},
  {code:'811600',category:'Poulet',name:'Poitrine de poulet farcie jambon fromage et asperge',format:'12 x 230g',origin:'Le poulet du Québec',price:134.0},
  {code:'666017',category:'Poulet',name:'Poitrine de poulet farcie jambon, fromage suisse',format:'12 x 200g',origin:'Produits Alimentaires LM',price:134.0},
  {code:'811120',category:'Poulet',name:'Poitrine de poulet farcie au risotto crémeux',format:'12 x 245g',origin:'Produits Alimentaires LM',price:134.0},
  {code:'811146',category:'Poulet',name:'Poitrine de poulet style parmigiana à gratinée',format:'10 unités',origin:'Produits Alimentaires LM',price:139.0},
  {code:'811137',category:'Poulet',name:'Poulet farci aux saveurs italiennes traditionnelles',format:'12 x 205g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'666004',category:'Poulet',name:'Boite découverte poulets farcis',format:'12un',origin:'Produits Alimentaires LM',price:159.0},
  {code:'666002',category:'Poulet',name:'Boite découverte viande en sauce',format:'8un',origin:'Produits Alimentaires LM',price:139.0},
  {code:'811425',category:'Poulet',name:'Brochette de poulet Souvlaki aux herbes méditerranéennes',format:'9 x 2 x 110g',origin:'Produits Alimentaires LM',price:74.0},
  {code:'811126',category:'Poulet',name:'Trio de brochettes de poulet aux saveurs variées',format:'3 x (8 x 155g)',origin:'Produits Alimentaires LM',price:99.0},
  {code:'811574',category:'Poulet',name:'Tournedos de poulet tendre nature',format:'16 x 140g',origin:'Le poulet du Québec',price:124.0},
  {code:'821338',category:'Poulet',name:'Tournedos de poulet mariné BBQ',format:'16 X 140g',origin:'Le poulet du Québec',price:144.0},
  {code:'821352',category:'Poulet',name:'Tournedos de poulet miel et ail caramélisé',format:'16 x 140g',origin:'Le poulet du Québec',price:144.0},
  {code:'821334',category:'Poulet',name:'Tournedos de poulet aux épices méditerranéennes',format:'14 x 170g',origin:'Le poulet du Québec',price:144.0},
  {code:'811002',category:'Poulet',name:'Coq au porc érable et chipotle, sucré-fumé à souhait',format:'12 x 275g',origin:'Le poulet du Québec',price:144.0},
  {code:'821340',category:'Poulet',name:'Croquettes de poulet croustillantes',format:'2 x 1 kg',origin:'Produit Canadien',price:44.0},
  {code:'821409',category:'Poulet',name:'Filet de poulet pané doré et tendre',format:'2 kg',origin:'Produit Canadien',price:64.0},
  {code:'821807',category:'Poulet',name:'Poulet frit (Haut de cuisse) croustillant et juteux',format:'2 kg',origin:'Véritable',price:74.0},
  {code:'821374',category:'Poulet',name:'Burger de poulet pané gourmet',format:'1.6 kg',origin:'Produit Canadien',price:74.0},
  {code:'821369',category:'Poulet',name:'Ailes de poulet BBQ précuites à saveur fumée',format:'2 kg',origin:'Ferme des voltigeurs',price:64.0},
  {code:'821373',category:'Poulet',name:'Poulet Pop Corn croquant et amusant',format:'2 kg',origin:'Produit Canadien',price:74.0},
  {code:'821371',category:'Poulet',name:'Egg Rolls au poulet savoureux et croustillants',format:'+/-36 x 50g',origin:'Produit Canadien',price:84.0},
  {code:'821326',category:'Poulet',name:'Poulet Général Tao croustillant avec sauce sucrée-épicée',format:'2 kg viande 1kg sauce',origin:'Produit Canadien',price:124.0},
  {code:'600108',category:'Poulet',name:'Dinde hachée maigre de première qualité',format:'+/-2,5kg',origin:'La ferme Avibross',price:64.0},
  {code:'312021',category:'Poulet',name:'Dinde entière nourrie aux grains, tendre et savoureuse',format:'10-12 lbs',origin:'La ferme Avibross',price:69.0},
  {code:'151396',category:'Porc',name:'Porc haché savoureux et polyvalent',format:'10 x 500g',origin:'Le porc du Québec',price:99.0},
  {code:'151125',category:'Porc',name:'Escalope de porc tendre et délicate',format:'24 x 110g',origin:'Le porc du Québec',price:59.0},
  {code:'811301',category:'Porc',name:'Côtelette demi lune pour les petits appétits',format:'24 x 110g',origin:'Le porc du Québec',price:54.0},
  {code:'821350',category:'Porc',name:'Côtelette de porc avec os à saveur authentique',format:'12 x 140g',origin:'Le porc du Québec',price:59.0},
  {code:'150236',category:'Porc',name:'Tomahawk de porc impressionnant au goût intense',format:'12 x +/-300g',origin:'Le porc du Québec',price:134.0},
  {code:'821351',category:'Porc',name:'Filet de porc maigre et tendre',format:'3kg',origin:'Le porc du Québec',price:84.0},
  {code:'811975',category:'Porc',name:'Rôti de longe de porc juteux',format:'4 x 908g',origin:'Le porc du Québec',price:84.0},
  {code:'821346',category:'Porc',name:'Côtes levées nature prêtes à personnaliser',format:'5 x +/-850g',origin:'Le porc du Québec',price:94.0},
  {code:'AP2193',category:'Porc',name:'Côtes levées précuites colonel Bob (Hugo Girard)',format:'4un (1,9kg)',origin:'Véritable/ Hugo Girard',price:149.0},
  {code:'811147',category:'Porc',name:'Côtes levées précuites au whisky au goût riche',format:'3.8 kg',origin:'Produits Alimentaires LM',price:144.0},
  {code:'811162',category:'Porc',name:'Côtes levées BBQ précuites à saveur fumée et caramélisée',format:'2,5 kg',origin:'Produits Alimentaires LM',price:144.0},
  {code:'821805',category:'Porc',name:'Côtes levées précuites sel & poivre à personnaliser',format:'4un (1,6KG)',origin:'Véritable',price:74.0},
  {code:'811149',category:'Porc',name:'Médaillon de poc sauce côte levée',format:'6 x 500g',origin:'Produits Alimentaires LM',price:94.0},
  {code:'811133',category:'Porc',name:'Médaillon de porc miel-moutarde précuit tendre et gourmand',format:'8 x 450g',origin:'Produits Alimentaires LM',price:94.0},
  {code:'AP5368',category:'Porc',name:'Boîte de kefta mixte savoureuse: Fines Herbes, Cheeseburger, Méditérannéen, Érable, Oignons caramélisés et Balsamique',format:'2,5kg',origin:'Viande de l\'est',price:94.0},
  {code:'811104',category:'Porc',name:'Brochettes de porc Souvlaki aux parfums méditerranéens',format:'9 x 2 x 110 g',origin:'Produits Alimentaires LM',price:74.0},
  {code:'821250',category:'Porc',name:'Côte de porc érable-chipotle sucré-fumé',format:'12 x 250g',origin:'Le porc du Québec',price:104.0},
  {code:'821331',category:'Porc',name:'Côtelettes de porc marinées façon Souvlaki',format:'8 x 400g',origin:'Le porc du Québec',price:79.0},
  {code:'821332',category:'Porc',name:'Côtelettes de porc parfumées sauce Teriyaki',format:'8 x 400g',origin:'Le porc du Québec',price:79.0},
  {code:'821806',category:'Porc',name:'Osso buco de porc mijoté façon italienne',format:'3 x 2 x 340g',origin:'Véritable',price:79.0},
  {code:'811163',category:'Porc',name:'Porc effiloché tendre et savoureux',format:'10 x 200g',origin:'Produits Alimentaires LM',price:92.0},
  {code:'106099',category:'Porc',name:'Bacon fumé tranché croustillant',format:'10 x 250g',origin:'Rouge Viande',price:64.0},
  {code:'106098',category:'Porc',name:'Épaule de porc fumée (Jambon sur os)',format:'2 x +/-3.5 kg',origin:'Rouge Viande',price:109.0},
  {code:'107590',category:'Porc',name:'Saucisses déjeuner bacon & cheddar fondant',format:'9 x 6un',origin:'Méchant Régal',price:89.0},
  {code:'107591',category:'Porc',name:'Saucisses déjeuner aux fines herbes parfumées',format:'9 x 6un',origin:'Méchant Régal',price:89.0},
  {code:'107592',category:'Porc',name:'Saucisses déjeuner porc & bœuf pour un goût généreux',format:'9 x 6un',origin:'Méchant Régal',price:84.0},
  {code:'107593',category:'Porc',name:'Trio de saucisses déjeuner aux saveurs variées',format:'9 x 6un',origin:'Méchant Régal',price:89.0},
  {code:'107578',category:'Porc',name:'Saucisses échalote et vin blanc raffinées',format:'8 x 4un',origin:'Méchant Régal',price:84.0},
  {code:'107579',category:'Porc',name:'Saucisses Toulouse traditionnelles',format:'8 x 4un',origin:'Méchant Régal',price:84.0},
  {code:'107584',category:'Porc',name:'Saucisses suisses précuites au goût délicat',format:'8 x 4un',origin:'Méchant Régal',price:89.0},
  {code:'107576',category:'Porc',name:'Saucisses style pizza, gourmandes et amusantes',format:'8 x 4un',origin:'Méchant Régal',price:84.0},
  {code:'107587',category:'Porc',name:'Saucisses jalapeños & cheddar légèrement relevées',format:'8 x 4un',origin:'Méchant Régal',price:79.0},
  {code:'107585',category:'Porc',name:'Merguez 100% agneau au goût authentique',format:'8 x 4un',origin:'Méchant Régal',price:104.0},
  {code:'107580',category:'Porc',name:'Saucisses italiennes fortes, relevées et aromatiques',format:'8 x 4un',origin:'Méchant Régal',price:84.0},
  {code:'107581',category:'Porc',name:'Saucisses italiennes douces aux herbes fines',format:'8 x 4un',origin:'Méchant Régal',price:84.0},
  {code:'107582',category:'Porc',name:'Saucisses canneberge et érable',format:'8 x 4un',origin:'Méchant Régal',price:84.0},
  {code:'107575',category:'Porc',name:'Saucisses au gouda fumé crémeux',format:'8 x 4un',origin:'Méchant Régal',price:89.0},
  {code:'107583',category:'Porc',name:'Saucisses saveur côte levée BBQ',format:'8 x 4un',origin:'Méchant Régal',price:84.0},
  {code:'107588',category:'Porc',name:'Saucisses migneron et canneberges gourmandes',format:'8 x 4un',origin:'Méchant Régal',price:109.0},
  {code:'107574',category:'Porc',name:'Boite assortie 8 saveurs de saucisses',format:'8 x 4un',origin:'Méchant Régal',price:89.0},
  {code:'107577',category:'Porc',name:'Saucisses bacon & cheddar riches en goût',format:'8 x 4un',origin:'Méchant Régal',price:84.0},
  {code:'923002',category:'Porc',name:'Saucisse Power Dog au bacon, format généreux',format:'12 x 450g',origin:'Méchant Régal',price:154.0},
  {code:'666018',category:'Porc',name:'Boite mixe saucisses de gibier',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:86.0},
  {code:'104308',category:'Porc',name:'Saucisses bacon & cheddar sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:76.0},
  {code:'104306',category:'Porc',name:'Saucisses brocoli-cheddar sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:76.0},
  {code:'104300',category:'Porc',name:'Saucisses échalotes et vin blanc raffinées sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:76.0},
  {code:'104082',category:'Porc',name:'Saucisses italiennes douces sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:76.0},
  {code:'104301',category:'Porc',name:'Saucisses italiennes fortes sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:76.0},
  {code:'104304',category:'Porc',name:'Saucisses jambon et érable sucré-salé sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:76.0},
  {code:'104310',category:'Porc',name:'Merguez porc & agneau sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:76.0},
  {code:'104084',category:'Porc',name:'Saucisse Toulouse traditionnelle sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:76.0},
  {code:'520846',category:'Porc',name:'Saucisses goût côte levée BBQ sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:76.0},
  {code:'821538',category:'Porc',name:'Boite mixe saucisses, sans gluten',format:'8 x 3 x 100g',origin:'Délices de charlevoix',price:79.0},
  {code:'821203',category:'Poisson',name:'Filet de sole délicat et savoureux',format:'1,82kg',origin:'Produit du Québec',price:64.0},
  {code:'211565',category:'Poisson',name:'Longe d’aiglefin tendre au goût fin',format:'4oz x +/- 15 un (Total 1.82 kg)',origin:'Produit du Québec',price:84.0},
  {code:'821298',category:'Poisson',name:'Longe de morue blanche fondante',format:'5oz x +/-12 un (Total 2kg)',origin:'Produit du pacifique',price:94.0},
  {code:'821537',category:'Poisson',name:'Morue de Terre Neuve premium au goût raffiné',format:'10 x 170g',origin:'Produit d\'Islande',price:154.0},
  {code:'821316',category:'Poisson',name:'Filet de doré tendre et feuilleté',format:'2 kg',origin:'Produit Canadien',price:114.0},
  {code:'821233',category:'Poisson',name:'Tilapia doux et polyvalent',format:'2 lbs',origin:'Produit d\'Asie',price:49.0},
  {code:'821267',category:'Poisson',name:'Pavé de saumon riche et moelleux',format:'12 x 170g',origin:'Produit Canadien',price:142.0},
  {code:'821532',category:'Poisson',name:'Saumon King biologique au goût beurré et noble',format:'1.82 kg          (un de 6oz)',origin:'Produit Canadien',price:149.0},
  {code:'821473',category:'Poisson',name:'Omble chevalier nordique délicat et fraîchement préparé',format:'2,27kg',origin:'Produit du Québec',price:104.0},
  {code:'821257',category:'Poisson',name:'Filet de truite tendre et savoureux',format:'1.82 kg',origin:'Produit du Québec',price:119.0},
  {code:'821523',category:'Poisson',name:'Steak de thon rouge yellowtail de qualité sashimi',format:'13 x 170g',origin:'Produit du Québec',price:134.0},
  {code:'821324',category:'Poisson',name:'Thon rouge saku prêt à trancher pour sushi',format:'8 x 280g',origin:'Produit du Québec',price:184.0},
  {code:'666025',category:'Poisson',name:'Tranche de saumon serrano',format:'10 x 100g',origin:'Produit du Québec',price:119.0},
  {code:'666026',category:'Poisson',name:'Bonbon de saumon fumé à chaud',format:'12 x 100g',origin:'Petit poisson content',price:149.0},
  {code:'666005',category:'Poisson',name:'Boite découverte poisson du québec',format:'7 produits',origin:'Petit poisson content',price:196.0},
  {code:'666001',category:'Poisson',name:'Boite découverte saumon',format:'12un',origin:'Produits Alimentaires LM',price:159.0},
  {code:'666003',category:'Poisson',name:'Boite découverte fruits de mer',format:'12un',origin:'Produits Alimentaires LM',price:174.0},
  {code:'AP4659',category:'Poisson',name:'Boite découverte saumon fumé artisanal de la Gaspésie',format:'1,7kg',origin:'Produit du Québec',price:134.0},
  {code:'821347',category:'Poisson',name:'Petites crevettes nordiques douces et délicates',format:'5 x 400g',origin:'Produit du Québec',price:94.0},
  {code:'821376',category:'Poisson',name:'Crevettes blanches jumbo, parfaites pour le grill',format:'1,36kg',origin:'Produit d\'Asie',price:109.0},
  {code:'821375',category:'Poisson',name:'Crevettes argentines sauvages à la chair rouge et sucrée',format:'2 x 908g',origin:'Produit d\'Asie',price:124.0},
  {code:'821349',category:'Poisson',name:'Crevettes argentines ouvertes papillon pour cuisson parfaite',format:'4 x 454g',origin:'Produit d\'Asie',price:129.0},
  {code:'821318',category:'Poisson',name:'Crevettes papillon ail & panko croustillantes',format:'1.82 kg',origin:'Produit d\'Asie',price:139.0},
  {code:'821348',category:'Poisson',name:'Petits pétoncles tendres et polyvalents',format:'5 x 400g',origin:'Produit Canadien',price:104.0},
  {code:'821531',category:'Poisson',name:'Gros pétoncles qualité restaurant',format:'1,82kg',origin:'Produit Canadien',price:204.0},
  {code:'821714',category:'Poisson',name:'Queue d’homard généreuse et délicate',format:'+/- 18un (Total1.82 kg)',origin:'Produit du Québec',price:214.0},
  {code:'821322',category:'Poisson',name:'Queue de langouste raffinée au goût riche',format:'1,4 kg',origin:'Produit des caraïbes',price:224.0},
  {code:'821355',category:'Poisson',name:'Saumon mariné cuit sur cèdre, érable & BBQ',format:'8 x 240g',origin:'Produit du Québec',price:144.0},
  {code:'821323',category:'Poisson',name:'Doigts de saumons fumés artisanal au goût riche',format:'1.5 kg',origin:'Produit du Québec',price:154.0},
  {code:'821733',category:'Poisson',name:'Saumon fumé tranché prêt à servir',format:'20 x 65g',origin:'Produit du Québec',price:204.0},
  {code:'821319',category:'Poisson',name:'Brochettes de saumon érable caramélisé',format:'12 x 150g',origin:'Produit du Québec',price:134.0},
  {code:'821320',category:'Poisson',name:'Brochettes de saumon aux trois poivres aromatiques',format:'12 x 150g',origin:'Produit du Québec',price:134.0},
  {code:'610360',category:'Poisson',name:'Truite farcie crevettes & pétoncles gourmet',format:'10 x 200g',origin:'Produits Alimentaires LM',price:164.0},
  {code:'811142',category:'Poisson',name:'Filet de sole farci aux saveurs de la mer',format:'7 x 350g',origin:'Produits Alimentaires LM',price:99.0},
  {code:'811141',category:'Poisson',name:'Saumon grillé nappé de sauce au vin blanc',format:'8 x 285g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'811140',category:'Poisson',name:'Saumon farci aux crevettes fondant',format:'10 x 160g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'811173',category:'Poisson',name:'Saumon mariné aux fines herbes parfumées',format:'10 x 170g',origin:'Produits Alimentaires LM',price:134.0},
  {code:'821353',category:'Poisson',name:'Bâtonnets de poisson croustillants',format:'2.27 kg',origin:'Produit du Québec',price:54.0},
  {code:'213136',category:'Poisson',name:'Fish & Chips aux filets de goberge dorés',format:'3 kg +/-18 unitées',origin:'Produit du Québec',price:104.0},
  {code:'213178',category:'Poisson',name:'Fish & Chips de morue tendre de qualité supérieure',format:'3kg +/- 18 unitées',origin:'Produit du Québec',price:154.0},
  {code:'821356',category:'Poisson',name:'Portions de flétan délicates et haut de gamme',format:'2kg                 (un. de  6-7oz)',origin:'Produit du Québec',price:174.0},
  {code:'821336',category:'Veau et Agneau',name:'Côtelette d’agneau tendre et juteuse',format:'+/-2,3kg',origin:'Viande de l\'est',price:174.0},
  {code:'821337',category:'Veau et Agneau',name:'Carré d’agneau premium, délicatement persillé',format:'2.6 kg',origin:'Viande de l\'est',price:204.0},
  {code:'520021',category:'Veau et Agneau',name:'Jarret d’agneau nature, cuisson lente et fondante',format:'12 x 525g',origin:'Viande de l\'est',price:244.0},
  {code:'AP5369',category:'Veau et Agneau',name:'Sélection mixte d’agneau – Fondue, Burger, Gigot, Merguez, Kefta',format:'2,5kg',origin:'Produit du Québec',price:154.0},
  {code:'811226',category:'Veau et Agneau',name:'Escalope de veau extra fine et délicate',format:'16 x 110g',origin:'Produit du Québec',price:124.0},
  {code:'508013',category:'Veau et Agneau',name:'Veau haché qualité bouchère',format:'6 x 454g',origin:'Produit du Québec',price:74.0},
  {code:'821412',category:'Veau et Agneau',name:'Bavette de veau tendre à souhait',format:'12 x 200g',origin:'Produit du Québec',price:134.0},
  {code:'927835',category:'Veau et Agneau',name:'Côte de veau  – qualité supérieure, Halal',format:'4 x +/- 450g',origin:'Viande de l\'est',price:119.0},
  {code:'923832',category:'Gibier',name:'Cerf haché extra maigre – riche en saveur, parfait pour burgers et sauces',format:'10 x 300g',origin:'Canabec',price:144.0},
  {code:'622616',category:'Gibier',name:'Médaillon de cerf - Noble et sauvage',format:'10 x 200g',origin:'Canabec',price:154.0},
  {code:'520598',category:'Gibier',name:'Médaillon de wapiti – viande noble, tendre et raffinée',format:'10 x 200g',origin:'Canabec',price:164.0},
  {code:'121477',category:'Gibier',name:'Bison haché extra maigre – goût authentique, faible en gras',format:'8 x 400g',origin:'Canabec',price:149.0},
  {code:'522617',category:'Gibier',name:'Médaillon de bison – texture délicate et saveur sauvage',format:'10 x 200g',origin:'Canabec',price:174.0},
  {code:'522152',category:'Gibier',name:'Contre-filet de bison – coupe premium, juteuse et pleine de caractère',format:'2,8kg',origin:'Canabec',price:264.0},
  {code:'522153',category:'Gibier',name:'Entrecôte de bison – marbrage léger et tendreté remarquable',format:'2,8kg',origin:'Canabec',price:244.0},
  {code:'121487',category:'Gibier',name:'Cheval haché – traditionnel et savoureux, idéal en cuisine maison',format:'8 x +/-400g',origin:'Canabec',price:104.0},
  {code:'821330',category:'Gibier',name:'Magret de canard – un classique fondant et gourmand',format:'10 x 350gr',origin:'Canabec',price:144.0},
  {code:'821354',category:'Gibier',name:'Cuisse de canard confit – cuisson lente, saveurs irrésistibles',format:'10 x 325g',origin:'Canabec',price:144.0},
  {code:'811167',category:'Gibier',name:'Burger de canard – une expérience savoureuse et différente',format:'18 un.',origin:'Produits Alimentaires LM',price:174.0},
  {code:'666021',category:'Gibier',name:'Boite dégustation produits de canard',format:'6 produits',origin:'Lac brome',price:149.0},
  {code:'821327',category:'Gibier',name:'Tourte au canard confit – feuilletée, généreuse et maison',format:'12 x 170g',origin:'Produits Alimentaires LM',price:174.0},
  {code:'821344',category:'Gibier',name:'Fondue bœuf – tranches fines, tendres et savoureuses',format:'6 x 400g',origin:'Méchant Régal',price:109.0},
  {code:'920159',category:'Gibier',name:'Fondue poulet – fondante et légère',format:'10 x 200g',origin:'Méchant Régal',price:104.0},
  {code:'522039',category:'Gibier',name:'Trio fondue (3x bœuf – 3x porc – 3x poulet) – le plaisir en variété',format:'9 x 200g',origin:'Méchant Régal',price:99.0},
  {code:'522037',category:'Gibier',name:'Fondue combo (bison – canard – cerf – agneau – wapiti) – expérience découverte unique',format:'10 x 200g',origin:'Canabec',price:144.0},
  {code:'AP4242',category:'Plats',name:'Assaisonements pour aliments - Épices à steak AP',format:'675g',origin:'Produit du Québec',price:14.99},
  {code:'AP4344',category:'Plats',name:'Boîte Découverte « Sauces & Épices Sandra Foodie » – Une sélection raffinée de saveurs',format:'2 sauces         3 épices',origin:'Sandra Foodie',price:64.0},
  {code:'821366',category:'Plats',name:'Gratin Dauphinois parfaitement gratinées au four, dorées à souhait.',format:'30 x 110g',origin:'Produit du Québec',price:104.0},
  {code:'811122',category:'Plats',name:'Tartare deux saumons - agréable en bouche',format:'8 x 150g',origin:'Produits Alimentaires LM',price:129.0},
  {code:'811129',category:'Plats',name:'Tartare de saumon asiatique – Notes sésame et citron',format:'8 x 150g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'811128',category:'Plats',name:'Tartare de thon rouge – Pur, raffiné et fondant',format:'8 x 150g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'811125',category:'Plats',name:'Tartare de bœuf classique – Le grand intemporel',format:'8 x 130g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'811143',category:'Plats',name:'Tartare de bœuf à l’italienne – Parmesan, basilic, huile d’olive',format:'8 x 130g',origin:'Produits Alimentaires LM',price:134.0},
  {code:'811123',category:'Plats',name:'Tartare de canard – Goût délicat et texture fondante',format:'8 x 130g',origin:'Produits Alimentaires LM',price:154.0},
  {code:'811127',category:'Plats',name:'Tartare de bison l\'asiatique',format:'9 x 130g',origin:'Produits Alimentaires LM',price:154.0},
  {code:'302001',category:'Plats',name:'Feuilleté saumon – Doré et généreux',format:'8 x 240g',origin:'Produits Alimentaires LM',price:134.0},
  {code:'821224',category:'Plats',name:'Feuilleté fruits de mer – Crémeux et croustillant',format:'8 x 270g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'811169',category:'Plats',name:'Feuilleté de poulet – Sauce maison et pâte légère',format:'10 unités',origin:'Produits Alimentaires LM',price:104.0},
  {code:'811130',category:'Plats',name:'Feuilleté mexicain – Relevé et savoureux',format:'8 x 185g',origin:'Produits Alimentaires LM',price:94.0},
  {code:'811159',category:'Plats',name:'Poulet Wellington – Volaille tendre en croûte dorée',format:'8 x 250g',origin:'Produits Alimentaires LM',price:114.0},
  {code:'811144',category:'Plats',name:'Saumon Wellington – Raffiné et plein de finesse',format:'8 x 250g',origin:'Produits Alimentaires LM',price:114.0},
  {code:'811145',category:'Plats',name:'Homard Wellington – Élégant, riche et gourmet',format:'8 x 250g',origin:'Produits Alimentaires LM',price:134.0},
  {code:'821359',category:'Plats',name:'Triangles de fromage – Chaud, croustillant et fondant',format:'2.27 kg',origin:'Produit du Québec',price:69.0},
  {code:'666030',category:'Plats',name:'Batonnet de fromage',format:'2,27Kg',origin:'Produit du Québec',price:79.0},
  {code:'821811',category:'Plats',name:'Acras crevettes Gaspésie – Herbes fraîches et saveurs de mer',format:'48un',origin:'Véritable',price:114.0},
  {code:'211461',category:'Plats',name:'Fondue parmesan aux crevettes - super fromagé',format:'3 x 6 un',origin:'Véritable',price:94.0},
  {code:'211464',category:'Plats',name:'Fondue parmesan au saumon fumée - gout de la mer',format:'6 x 4 un',origin:'Véritable',price:94.0},
  {code:'861279',category:'Plats',name:'Fondue parmesan fruits de mer – Crémeuse et généreuse',format:'6 x 4        (70g)',origin:'Produit du Québec',price:94.0},
  {code:'666031',category:'Plats',name:'Fondue 4 fromages – Onctueuse et réconfortante',format:'2.27 kg',origin:'Produit du Québec',price:89.0},
  {code:'821809',category:'Plats',name:'Fondue homard & brandy – Prestige et finesse',format:'24un',origin:'Véritable',price:74.0},
  {code:'821810',category:'Plats',name:'Fondue 5 fromages du Québec – Terroir pur et fondant',format:'24un',origin:'Véritable',price:69.0},
  {code:'611244',category:'Plats',name:'Fromage en grains pané – Croustillant à souhait',format:'2.27 kg',origin:'Produit du Québec',price:79.0},
  {code:'821594',category:'Plats',name:'Sauce à spaghetti – Longuement mijotée et savoureuse',format:'6 x 500g',origin:'Produits Alimentaires LM',price:84.0},
  {code:'811161',category:'Plats',name:'Sauce fruits de mer – Crémeuse et généreuse',format:'10 x 400g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'213307',category:'Plats',name:'Petite coquille fruits de mer & patates – Réconfort et gourmandise',format:'10 x 150g',origin:'Produits Alimentaires LM',price:99.0},
  {code:'811165',category:'Plats',name:'Coquille fruits de mer & patates – Réconfort et gourmandise',format:'10 x 275g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'612033',category:'Plats',name:'Coquille de homard – Crémeuse et raffinée',format:'10 x 280g',origin:'Produit du Québec',price:184.0},
  {code:'555008',category:'Plats',name:'Tourtière - Traditionnellement chaleureuse',format:'2 x 1kg',origin:'Produit du Québec',price:124.0},
  {code:'821592',category:'Plats',name:'Pâté au poulet – Classique maison et doré',format:'510g',origin:'Produit du Québec',price:16.0},
  {code:'821590',category:'Plats',name:'Pâté à la viande – Riche et généreux',format:'510g',origin:'Produit du Québec',price:14.0},
  {code:'821593',category:'Plats',name:'Pâté mexicain – Relevé et savoureux',format:'510g',origin:'Produit du Québec',price:16.0},
  {code:'821591',category:'Plats',name:'Pâté au saumon – Crémeux et traditionnel',format:'510g',origin:'Produit du Québec',price:15.0},
  {code:'821596',category:'Plats',name:'Tacos Cochinita – Porc effiloché parfumé',format:'8 x 500g',origin:'Taco Foods',price:109.0},
  {code:'821597',category:'Plats',name:'Tacos Fajitas de poulet – Poêlé et épicé juste comme il faut',format:'8 x 500g',origin:'Taco Foods',price:124.0},
  {code:'821598',category:'Plats',name:'Tacos Tinga – Poulet mijoté et goûteux',format:'8 x 500g',origin:'Taco Foods',price:134.0},
  {code:'821599',category:'Plats',name:'Tacos Barbacoa – Bœuf tendre et aromatique',format:'8 x 500g',origin:'Taco Foods',price:164.0},
  {code:'811134',category:'Plats',name:'Nouilles chinoises – Wok parfumé et légumes croquants',format:'8 x 275g',origin:'Produits Alimentaires LM',price:74.0},
  {code:'811135',category:'Plats',name:'Pizza fruits de mer – Garniture généreuse',format:'8un/cs',origin:'Produits Alimentaires LM',price:89.0},
  {code:'811168',category:'Plats',name:'Pizza saumon fumé – Finesse et fraîcheur',format:'8 un/cs',origin:'Produits Alimentaires LM',price:109.0},
  {code:'811121',category:'Plats',name:'Rouleau de pizza – Gourmand et fromage fondant',format:'30 unités',origin:'Produits Alimentaires LM',price:79.0},
  {code:'811136',category:'Plats',name:'Poulet Alfredo – Sauce onctueuse et savoureuse',format:'8 x 400g',origin:'Produits Alimentaires LM',price:129.0},
  {code:'811138',category:'Plats',name:'Poulet forestière – Champignons parfumés',format:'8 x 400g',origin:'Produits Alimentaires LM',price:129.0},
  {code:'811139',category:'Plats',name:'Poulet curry coco - Douceur exotique',format:'8 x 400g',origin:'Produits Alimentaires LM',price:144.0},
  {code:'811148',category:'Plats',name:'Crevettes curry coco – Velouté et parfumé',format:'8 x 400g',origin:'Produits Alimentaires LM',price:144.0},
  {code:'811154',category:'Plats',name:'Sauce homard & poireau – Finesse et élégance',format:'8 x 300g',origin:'Produits Alimentaires LM',price:154.0},
  {code:'811155',category:'Plats',name:'Pâté chinois – Le classique réconfort',format:'8 x 400g',origin:'Produits Alimentaires LM',price:84.0},
  {code:'811156',category:'Plats',name:'Bœuf bourguignon – Longuement mijoté au vin rouge',format:'8 x 350g',origin:'Produits Alimentaires LM',price:134.0},
  {code:'811166',category:'Plats',name:'Pot en pot – Croûte dorée et garniture généreuse',format:'8 x 350g',origin:'Produits Alimentaires LM',price:124.0},
  {code:'811131',category:'Plats',name:'Mac & cheese deluxe – Crémeux et irrésistible',format:'8 x 350g',origin:'Produits Alimentaires LM',price:99.0},
  {code:'811132',category:'Plats',name:'Mac & cheese homard truffe – Luxe gourmand',format:'8 x 350g',origin:'Produits Alimentaires LM',price:144.0},
  {code:'811158',category:'Plats',name:'Lasagne fruits de mer – Crémeuse et raffinée',format:'8 x 350g',origin:'Produits Alimentaires LM',price:114.0},
  {code:'811160',category:'Plats',name:'Lasagne à la viande – Gratinée et généreuse',format:'8 x 350g',origin:'Produits Alimentaires LM',price:99.0},
  {code:'811157',category:'Plats',name:'Macaroni à la viande – Familial et savoureux',format:'8 x 350g',origin:'Produits Alimentaires LM',price:69.0},
  {code:'811933',category:'Desserts',name:'Gâteau crumble aux framboises – Moelleux, fruité et croustillant',format:'4 x 400g',origin:'Hafner',price:89.0},
  {code:'811934',category:'Desserts',name:'Gâteau aux carottes – Tendre, épicé et gourmand',format:'4 x 485g',origin:'Hafner',price:89.0},
  {code:'811935',category:'Desserts',name:'Mousse aux trois chocolats – Onctueuse et irrésistible',format:'24 x 80g',origin:'Hafner',price:59.0},
  {code:'811936',category:'Desserts',name:'Mousse aux framboises – Légère, fraîche et fruitée',format:'24 x 80g',origin:'Hafner',price:54.0},
  {code:'555003',category:'Desserts',name:'Tarte aux bleuets - Sucrée et généreuse',format:'650g',origin:'PAG',price:10.0},
  {code:'555001',category:'Desserts',name:'Tarte à la fraise et rubarbe - Riche et doré',format:'650g',origin:'PAG',price:10.0},
  {code:'555004',category:'Desserts',name:'Tarte aux framboises - Gourmande et savoureuse',format:'650g',origin:'PAG',price:10.0},
  {code:'555002',category:'Desserts',name:'Tarte aux 3 fruits - Éclatante de saveur',format:'650g',origin:'PAG',price:10.0},
];

export const PRODUCT_MAP = Object.fromEntries(PRODUCTS.map(p => [p.code, p]));